#ifndef THINPAD_H__
#define THINPAD_H__



#define THINPAD_SERIAL_UART USART6
#define THINPAD_SERIAL_UART_IT_HANDLER USART6_IRQHandler
#define THINPAD_SERIAL_UART_IRQ        USART6_IRQn

#define THINPAD_SERIAL_BAUD_MIN 1200
#define THINPAD_SERIAL_BAUD_MAX 888000
#define THINPAD_SERIAL_N2T_BUF_SIZE 1024
#define THINPAD_SERIAL_T2N_BUF_SIZE 1024


#endif